Settings.insert =
  abbreviations:
    "administrator": "admin"
    "administrators": "admins"
    "allocate": "alloc"
    "alternate": "alt"
    "at all": "et. al."
    "auxiliary": "aux"
    "biology": "bio"
    "boolean": "bool"
    "brewery": "brew"
    "current": "curr"
    "dictionary": "dict"
    "distribute": "dist"
    "error": "err"
    "exponent": "exp"
    "hovering": "hover"
    "jason": "JSON"
    "logger": "log"
    "kenneth": "ken"
    "markdown": "md"
    "mister": "Mr."
    "missus": "Mrs."
    "miss": "Miss"
    "miscellaneous": "misc"
    "package": "pkg"
    "previous": "prev"
    "regular expression": "regex"
    "street": "St"
    "square root": "sqrt"
    "user": "usr"
    "victor": "Vic"
    "winter": "linter"
