Settings.web =
  websites:
    "alpha": "https://www.wolframalpha.com/"
    "amazon": "https://smile.amazon.com"
    "bing": "https://bing.com"
    "calendar": "https://calendar.google.com"
    "docs": "https://docs.google.com"
    "drive": "https://drive.google.com"
    "duck": "https://www.duckduckgo.com"
    "facebook": "https://facebook.com"
    "gmail": "https://gmail.com"
    "hero": "https://dashboard.heroku.com/apps"
    "linkedin": "https://www.linkedin.com/"
    "local": "http://localhost:8080"
    "medium": "https://medium.com/"
    "twitter": "https://twitter.com/"
