Settings.window = windowPositions:
  "big right":
      x: .333
      y: 0
      width: .666
      height: 1
  "big left":
      x: 0
      y: 0
      width: .666
      height: 1
  "big top":
      x: 0
      y: 0
      width: 1
      height: .666
  "big bottom":
      x: 0
      y: .333
      width: 1
      height: .666
  "mostly left":
      x: 0
      y: 0
      width: .75
      height: 1
  "mostly right":
      x: .25
      y: 0
      width: .75
      height: 1
  "super left":
      x: 0
      y: 0
      width: .85
      height: 1
  "super right":
      x: .15
      y: 0
      width: .85
      height: 1
  "quarter left":
      x: 0
      y: 0
      width: .25
      height: 1
  "quarter right":
      x: .75
      y: 0
      width: .25
      height: 1
  "third left":
      x: 0
      y: 0
      width: .333
      height: 1
  "third right":
      x: .666
      y: 0
      width: .333
      height: 1
  "third middle":
      x: .333
      y: 0
      width: .333
      height: 1
  "third top":
      x: 0
      y: 0
      width: 1
      height: .333
  "third bottom":
      x: 0
      y: .666
      width: 1
      height: .333
